variant = "loose"

[[issues]]
file = "src/EnumTrait.php"
code = "less-specific-nested-argument-type"
message = "Argument type mismatch for argument #1 of `array_combine`: expected `array<array-key, ('K.array_combine() extends array-key)>`, but provided type `array<array-key, mixed>` is less specific."
count = 1

[[issues]]
file = "src/EnumTrait.php"
code = "less-specific-nested-argument-type"
message = "Argument type mismatch for argument #1 of `array_map`: expected `(callable(mixed): mixed)|(callable(mixed, ('S.array_map() extends mixed)): mixed)|null`, but provided type `(callable(...mixed): mixed)|string` is less specific."
count = 1

[[issues]]
file = "src/EnumTrait.php"
code = "less-specific-return-statement"
message = 'Returned type `(webware\htmx\enumtrait&BackedEnum&backedenum&backedenum&static)|BackedEnum` is less specific than the declared return type `(webware\htmx\enumtrait&backedenum&static)|null` for function `Webware\Htmx\EnumTrait::tryFromName`.'
count = 1

[[issues]]
file = "src/EnumTrait.php"
code = "less-specific-return-statement"
message = 'Returned type `array<array-key, mixed>` is less specific than the declared return type `array<string, string>` for function `Webware\Htmx\EnumTrait::toArray`.'
count = 2

[[issues]]
file = "src/EnumTrait.php"
code = "template-constraint-violation"
message = "Argument type mismatch for template `K`."
count = 1

[[issues]]
file = "src/Request/ServerRequestFilter.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(0)` accessed on `array<array-key, string>`."
count = 2

[[issues]]
file = "src/View/LaminasRenderer.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `Webware\Htmx\View\LaminasRenderer::prepareBody`: expected `Laminas\View\Model\ModelInterface|false`, but found `Laminas\View\Model\ModelInterface|null`.'
count = 1

[[issues]]
file = "src/View/LaminasRenderer.php"
code = "nullable-return-statement"
message = 'Function `Webware\Htmx\View\LaminasRenderer::prepareBody` is declared to return `Laminas\View\Model\ModelInterface|false` but possibly returns a nullable value (inferred as `Laminas\View\Model\ModelInterface|null`).'
count = 1

[[issues]]
file = "src/View/LaminasRenderer.php"
code = "redundant-null-coalesce"
message = "Redundant null coalesce: left-hand side can never be `null` or undefined."
count = 1

[[issues]]
file = "src/View/LaminasRendererFactory.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 4
